CREATE TABLE IF NOT EXISTS markets (
    market_id TEXT PRIMARY KEY,
    venue TEXT NOT NULL,
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    expiration_date DATE NOT NULL,
    resolution_date DATE
);

CREATE TABLE IF NOT EXISTS market_prices (
    price_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    market_id TEXT NOT NULL REFERENCES markets(market_id),
    timestamp TIMESTAMP NOT NULL,
    yes_bid NUMERIC(8, 4),
    yes_ask NUMERIC(8, 4),
    mid_price NUMERIC(8, 4) NOT NULL,
    volume NUMERIC(18, 2),
    liquidity NUMERIC(18, 2),
    UNIQUE (market_id, timestamp)
);

CREATE TABLE IF NOT EXISTS events (
    event_id TEXT PRIMARY KEY,
    market_id TEXT NOT NULL REFERENCES markets(market_id),
    event_name TEXT NOT NULL,
    event_date DATE NOT NULL,
    outcome BOOLEAN
);

CREATE TABLE IF NOT EXISTS features (
    feature_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id TEXT NOT NULL REFERENCES events(event_id),
    timestamp TIMESTAMP NOT NULL,
    cpi_surprise NUMERIC(8, 4),
    unemployment_rate NUMERIC(8, 4),
    unemployment_change NUMERIC(8, 4),
    fed_funds_implied_prob NUMERIC(8, 4),
    fomc_tone_score NUMERIC(8, 4),
    days_to_event INTEGER NOT NULL,
    UNIQUE (event_id, timestamp)
);

CREATE TABLE IF NOT EXISTS model_predictions (
    prediction_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id TEXT NOT NULL REFERENCES events(event_id),
    timestamp TIMESTAMP NOT NULL,
    model_probability NUMERIC(8, 4) NOT NULL,
    lower_ci NUMERIC(8, 4) NOT NULL,
    upper_ci NUMERIC(8, 4) NOT NULL,
    market_probability NUMERIC(8, 4) NOT NULL,
    edge NUMERIC(8, 4) NOT NULL,
    signal TEXT NOT NULL,
    UNIQUE (event_id, timestamp)
);

CREATE INDEX IF NOT EXISTS idx_market_prices_market_time ON market_prices(market_id, timestamp);
CREATE INDEX IF NOT EXISTS idx_features_event_time ON features(event_id, timestamp);
CREATE INDEX IF NOT EXISTS idx_predictions_event_time ON model_predictions(event_id, timestamp);

